package main

import (
	"fmt"
	"net/http"

	"chirouter/handlers"
	"chirouter/store"
	_ "chirouter/docs" // Swagger docs generated by swag init

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Book API
// @version 1.0
// @description This is a sample Book API using Chi Router.
// @host localhost:3000
// @BasePath /
func main() {
	// 1. Initialize our in-memory data store
	bookStore := store.NewBookStore()

	// 2. Initialize our handler, injecting the store dependency
	bookHandler := handlers.NewBookHandler(bookStore)

	// 3. Create a new Chi router
	r := chi.NewRouter()

	// 4. Add global middlewares
	r.Use(middleware.Logger) // Logs every incoming request to the console
	r.Use(middleware.Recoverer) // Gracefully recovers from panics without crashing the server

	// 5. Serve Swagger UI
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// 6. Define a basic root endpoint
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Welcome to the Chi Router Book API! Visit /swagger/index.html for docs."))
	})

	// 7. Define a route group for all /books endpoints
	// This makes it so we don't have to type "/books" for every route!
	r.Route("/books", func(r chi.Router) {
		r.Get("/", bookHandler.GetAllBooks)       // GET /books
		r.Post("/", bookHandler.CreateBook)       // POST /books
		
		r.Get("/{id}", bookHandler.GetBookByID)   // GET /books/{id}
		r.Put("/{id}", bookHandler.UpdateBook)    // PUT /books/{id}
		r.Delete("/{id}", bookHandler.DeleteBook) // DELETE /books/{id}
	})

	// 8. Start the server
	fmt.Println("Server is running on port 3000...")
	fmt.Println("Swagger UI is available at http://localhost:3000/swagger/index.html")
	http.ListenAndServe(":3000", r)
}